// en.js
export default {
  login: {
    login: 'login',
    userName: 'userName',
    password: 'password',
  },
  homePage: {
    homePage: 'Home',
    PartnerSchool: 'PartnerSchool',
    Courses: 'Courses',
    SmartClassMatch: 'SmartClassMatch',
    Questionnaire: 'Questionnaire',
    MyCourse: 'MyCourse',
    personInfo: 'PersonInfo',
    MetricAnalysis: 'Metric Analysis',
    FeedbackCenter: 'Feedback Center',
    quit: 'Quit',
  },
  common: {
    inputPlaceholder: 'Please enter',
    PleaseEnterName: 'Please Enter Name',
    PleaseSelectGender: 'Please Select Gender',
    PleaseSelectAcademicQualifications:
      'Please Select Educational Qualifications',
    PleaseEnterSchoolCompany: 'Please enter School/Company',
    PleaseEnterPosition: 'Please Enter Position',
    PleaseEnterWorkingYears: 'Please Enter Working Years',
    PleaseEnterPhoneNumber: 'Please Enter PhoneNumber',
    PleaseEnterEmail: 'Please Enter Email',
    PleaseSelectDate: 'Please Select Date',
    Edit: 'Edit',
    Save: 'Save',
    PersonalData: 'PersonalData',
    CourseFilter: 'Course Filter',
    CourseResult: '{total} related courses found',
  },
  option: {
    Male: 'Male',
    Female: 'Female',
    JuniorHighSchool: 'Junior High School',
    HighSchool: 'High School',
    College: 'College',
    Undergraduate: 'Bachelor',
    postgraduate: 'Master',
    PhD: 'PhD',
  },
  personInfo: {
    personInfo: 'Personal Information',
    Name: 'Name',
    Gender: 'Gender',
    EducationalQualifications: 'Educational Qualifications',
    'School/Company': 'School/Company',
    Position: 'Position',
    WorkingYears: 'Working Years',
    Birthday: 'Birthday',
    Area: 'Area',
    PhoneNumber: 'Phone Number',
    Email: 'Email',
  },
};
