// en.js
export default {
  login: {
    login: 'login',
    userName: 'userName',
    password: 'password',
    userLogin: 'User login',
    welcome: 'Welcome back, please log in to your account',
    plsInputPhone: 'Please enter mobile phone number',
    plsInputPassword: 'Please enter password',
    Noaccount: `Don't have an account yet?`,
    RegisterNow: 'Register now',
    validMobilePhone: 'Please enter a valid mobile phone number',
    passwordEmpty: 'Password cannot be empty',
    phoneEmpty: 'Mobile number cannot be empty',
    passwordLength: 'The password length cannot be less than 6 characters',
    passwordFormat: 'Password must contain letters and numbers',
    createAccount: 'Create account',
    wonderfulJourney: 'Start your wonderful journey',
    haveAccount: 'Already have an account?',
    loginNow: 'Login Now',
  },
  homePage: {
    homePage: 'Home',
    PartnerSchool: 'PartnerSchool',
    Courses: 'Courses',
    SmartClassMatch: 'SmartClassMatch',
    Questionnaire: 'Questionnaire',
    MyCourse: 'MyCourse',
    personInfo: 'PersonInfo',
    MetricAnalysis: 'Metric Analysis',
    FeedbackCenter: 'Feedback Center',
    quit: 'Quit',
  },
  common: {
    inputPlaceholder: 'Please enter',
    PleaseEnterName: 'Please Enter Name',
    PleaseSelectGender: 'Please Select Gender',
    PleaseSelectAcademicQualifications:
      'Please Select Educational Qualifications',
    PleaseEnterSchoolCompany: 'Please enter School/Company',
    PleaseEnterPosition: 'Please Enter Position',
    PleaseEnterWorkingYears: 'Please Enter Working Years',
    PleaseEnterPhoneNumber: 'Please Enter PhoneNumber',
    PleaseEnterEmail: 'Please Enter Email',
    PleaseSelectDate: 'Please Select Date',
    Edit: 'Edit',
    Save: 'Save',
    PersonalData: 'PersonalData',
    CourseFilter: 'Course Filter',
    CourseResult: '{total} related courses found',
    person: 'Persons',
    collect: 'Collect',
    FeedbackCenter: 'Feedback Center',
    description: `Welcome to the Feedback Center! We will collect your subjective feedback on the system's usage experience and learning ability to optimize the recommendation algorithm and user experience.`,
    fillIn:
      'Click the button below to fill in the questionnaire. After submission, you will see your feedback results and trends in the chart below.',
    fillQuestionnaire: 'Fill out the feedback questionnaire',
    hint: 'Hint',
    NoData: 'No data',
    RequestCanceled: 'Request canceled:',
    loginInvalid: 'Your login has expired, please log in again',
    NoPermission: 'No permission to access this resource',
    ServerError: 'Server error, please try again later',
    RequestFailed: 'Request failed',
    NetworkAbnormal: 'The network is abnormal, please check the connection',
    AvatarSuccessfully: 'Avatar updated successfully',
    UploadFailed: 'Upload failed, please try again',
    UploadFailedFormat:
      'Upload failed, please check the network or file format',
    ImageLimit: 'Only JPG/PNG/GIF/WEBP format images can be uploaded',
    ImageSize: 'The size of the avatar image cannot exceed 10MB',
    UnnamedUser: 'Unnamed user',
  },
  option: {
    Male: 'Male',
    Female: 'Female',
    JuniorHighSchool: 'Junior High School',
    HighSchool: 'High School',
    College: 'College',
    Undergraduate: 'Bachelor',
    postgraduate: 'Master',
    PhD: 'PhD',
  },
  personInfo: {
    personInfo: 'Personal Information',
    Name: 'Name',
    Gender: 'Gender',
    EducationalQualifications: 'Educational Qualifications',
    'School/Company': 'School/Company',
    Position: 'Position',
    WorkingYears: 'Working Years',
    Birthday: 'Birthday',
    Area: 'Area',
    PhoneNumber: 'Phone Number',
    Email: 'Email',
  },
  questionnaire: {
    UsabilitySurvey: {
      q1_score: 'The system interface is easy to understand.',
      q2_score: 'I can complete various operations in the system smoothly.',
      q3_score:
        'The keywords and SRL label explanations are clear and easy to understand.',
      q4_score: 'The recommended course content aligns with my learning goals.',
      q5_score:
        'I can use the system independently without external assistance.',
      q6_score: 'The system’s loading and response speed is satisfactory.',
      q7_score: 'I am willing to use this recommendation system again.',
      q8_score: 'I would recommend this system to others.',
    },
    dimension: {
      q1_score: 'Motivation Regulation',
      q2_score: 'Goal Setting',
      q3_score: 'Time Management',
      q4_score: 'Self-Monitoring',
      q5_score: 'Help Seeking',
      q6_score: 'Task Strategy Use',
      q7_score: 'Self-Reflection',
    },
    Satisfaction: {
      StronglyAgree: 'Strongly Agree',
      Agree: 'Agree',
      generally: 'Generally',
      disagree: 'Disagree',
      StronglyDisagree: 'Strongly Disagree',
      InvalidScore: 'Invalid Score',
    },
    srlSurvey: {
      q1_score:
        'I am usually able to stay motivated, interested, and focused during the learning process because I set clear goals and take initiative?',
      q2_score:
        'Do I set clear goals and step-by-step plans for my learning, and actively track progress to achieve long-term objectives?',
      q3_score:
        'Am I able to manage my daily schedule efficiently, avoid procrastination, and prioritize tasks to enhance productivity?',
      q4_score:
        'During learning, do I monitor my attention, perform self-checks, and adjust based on feedback?',
      q5_score:
        'When facing learning difficulties, am I willing to seek help, ask questions, and get support through communication and collaboration?',
      q6_score:
        'Do I use various learning strategies and techniques (e.g., breaking down tasks, using methods) to solve problems more effectively?',
      q7_score:
        'Do I regularly reflect on experiences, analyze weaknesses, and proactively adjust strategies to improve my learning methods?',
    },
  },
  button: {
    submit: 'Submit',
    BatchOperations: 'Batch Operation',
    SelectAll: 'Select All',
    Cancel: 'Cancel',
    Delete: 'Delete',
  },
  message: {
    evaluate: 'Please rate the first 10 courses',
    submitSuccess: 'Evaluation results submitted successfully',
    submitFail: 'Submission failed, please try again later',
    rateEachQuestion: 'Please rate each question before submitting.',
    hint: 'Please complete both questionnaires before submitting.',
    selectCourse: 'Please select the course you want to uncollect first',
    cancelSuccess: 'Cancel collection successfully',
    cancelFail: 'Failed to cancel collection',
  },
  footer: {
    CourseEntry: 'Course Entry',
    AboutUs: 'About Us',
    ContactUs: 'Contact Us',
    PrivacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms Of Use',
    HelpCenter: 'Help Center',
    Feedback: 'Feedback',
    InfringementComplaint: 'Infringement Complaint',
  },
};
