// ms.js
export default {
  login: {
    login: 'Log Masuk',
    userName: 'Nama Pengguna',
    password: 'Kata Laluan',
    userLogin: 'Log Masuk Pengguna',
    welcome: 'Selamat kembali, sila log masuk ke akaun anda',
    plsInputPhone: 'Sila masukkan nombor telefon',
    plsInputPassword: 'Sila masukkan kata laluan',
    Noaccount: 'Tiada akaun?',
    RegisterNow: 'Daftar Sekarang',
    validMobilePhone: 'Sila masukkan nombor telefon yang sah',
    passwordEmpty: 'Kata laluan tidak boleh kosong',
    phoneEmpty: 'Nombor telefon tidak boleh kosong',
    passwordLength: 'Panjang kata laluan mestilah sekurang-kurangnya 6 aksara',
    passwordFormat: 'Kata laluan mesti mengandungi huruf dan nombor',
    createAccount: 'Cipta Akaun',
    wonderfulJourney: 'Mulakan perjalanan indah anda',
    haveAccount: 'Sudah ada akaun?',
    loginNow: 'Log masuk sekarang',
  },
  homePage: {
    homePage: 'Halaman Utama',
    PartnerSchool: 'Sekolah Rakan Kongsi',
    Courses: 'Kursus',
    SmartClassMatch: 'Padanan Kursus Pintar',
    Questionnaire: 'Soal Selidik',
    MyCourse: 'Kursus Saya',
    personInfo: 'Maklumat Peribadi',
    MetricAnalysis: 'Analisis Metrik',
    FeedbackCenter: 'Pusat Maklum Balas',
    quit: 'Log Keluar Selamat',
  },
  common: {
    inputPlaceholder: 'Sila masukkan',
    PleaseEnterName: 'Sila masukkan nama',
    PleaseSelectGender: 'Sila pilih jantina',
    PleaseSelectAcademicQualifications: 'Sila pilih kelayakan akademik',
    PleaseEnterSchoolCompany: 'Sila masukkan sekolah/syarikat',
    PleaseEnterPosition: 'Sila masukkan jawatan',
    PleaseEnterWorkingYears: 'Sila masukkan tempoh bekerja',
    PleaseEnterPhoneNumber: 'Sila masukkan nombor telefon',
    PleaseEnterEmail: 'Sila masukkan emel',
    PleaseSelectDate: 'Sila pilih tarikh',
    Edit: 'Sunting',
    Save: 'Simpan',
    PersonalData: 'Data Peribadi',
    CourseFilter: 'Penapis Kursus',
    CourseResult: 'Menjumpai {total} kursus berkaitan',
    person: 'Orang',
    collect: 'Simpan',
    FeedbackCenter: 'Pusat Maklum Balas',
    description:
      'Selamat datang ke Pusat Maklum Balas! Kami akan mengumpul maklum balas subjektif anda terhadap pengalaman penggunaan sistem dan kebolehan pembelajaran, untuk mengoptimumkan algoritma cadangan dan pengalaman pengguna.',
    fillIn:
      'Klik butang di bawah untuk mengisi soal selidik, dan lihat keputusan serta trend maklum balas anda dalam carta di bawah selepas dihantar.',
    fillQuestionnaire: 'Isi Soal Selidik',
    hint: 'Petua',
    NoData: 'Tiada data buat masa ini',
    RequestCanceled: 'Permintaan dibatalkan:',
    loginInvalid: 'Sesi tamat, sila log masuk semula',
    NoPermission: 'Tiada kebenaran untuk akses sumber ini',
    ServerError: 'Ralat pelayan, sila cuba kemudian',
    RequestFailed: 'Permintaan gagal',
    NetworkAbnormal: 'Rangkaian tidak normal, sila semak sambungan',
    AvatarSuccessfully: 'Avatar berjaya dikemas kini',
    UploadFailed: 'Muat naik gagal, sila cuba semula',
    UploadFailedFormat:
      'Muat naik gagal, sila semak rangkaian atau format fail',
    ImageLimit: 'Hanya gambar format JPG/PNG/GIF/WEBP dibenarkan',
    ImageSize: 'Saiz gambar avatar tidak boleh melebihi 10MB',
    UnnamedUser: 'Pengguna Tanpa Nama',
  },
  option: {
    Male: 'Lelaki',
    Female: 'Perempuan',
    JuniorHighSchool: 'Sekolah Menengah Rendah',
    HighSchool: 'Sekolah Menengah Atas',
    College: 'Kolej',
    Undergraduate: 'Ijazah Sarjana Muda',
    postgraduate: 'Sarjana',
    PhD: 'Doktor Falsafah',
  },
  personInfo: {
    personInfo: 'Maklumat Peribadi',
    Name: 'Nama',
    Gender: 'Jantina',
    EducationalQualifications: 'Kelayakan Akademik',
    'School/Company': 'Sekolah/Syarikat',
    Position: 'Jawatan',
    WorkingYears: 'Tahun Bekerja',
    Birthday: 'Tarikh Lahir',
    Area: 'Kawasan',
    PhoneNumber: 'Nombor Telefon',
    Email: 'Emel',
  },
  questionnaire: {
    srlSurvey: {
      q1_score:
        'Semasa belajar, adakah saya kekal bermotivasi, berminat dan fokus kerana saya menetapkan matlamat yang jelas dan memajukan pembelajaran secara aktif?',
      q2_score:
        'Adakah saya menetapkan matlamat dan pelan pembelajaran yang jelas, serta mengikuti kemajuan tugas untuk mencapai hasil jangka panjang?',
      q3_score:
        'Adakah saya mengatur masa harian dengan baik, mengelakkan penangguhan dan tugas berulang, serta mengutamakan tugasan secara optimum?',
      q4_score:
        'Semasa belajar, adakah saya menyedari tahap tumpuan saya dan melaksanakan semakan serta pelarasan sendiri secara tepat pada masanya?',
      q5_score:
        'Apabila menghadapi kesukaran dalam pembelajaran, adakah saya bersedia untuk meminta bantuan atau maklum balas secara aktif dan mendapatkan sokongan melalui kerjasama?',
      q6_score:
        'Adakah saya menggunakan pelbagai strategi atau teknik pembelajaran (seperti: pecahan tugasan, penggunaan jadual kaedah) untuk menyelesaikan masalah pembelajaran?',
      q7_score:
        'Adakah saya sering mengimbas kembali pengalaman selepas belajar, merenung kelemahan, dan menyesuaikan strategi untuk memperbaiki kaedah pembelajaran?',
    },
    dimension: {
      q1_score: 'Peraturan Motivasi',
      q2_score: 'Penetapan Matlamat',
      q3_score: 'Pengurusan Masa',
      q4_score: 'Pemantauan Kendiri',
      q5_score: 'Mencari Bantuan',
      q6_score: 'Penggunaan Strategi',
      q7_score: 'Refleksi dan Penyesuaian',
    },
    Satisfaction: {
      StronglyAgree: 'Sangat Setuju',
      Agree: 'Setuju',
      generally: 'Biasa Sahaja',
      disagree: 'Tidak Setuju',
      StronglyDisagree: 'Sangat Tidak Setuju',
      InvalidScore: 'Skor Tidak Sah',
    },
    UsabilitySurvey: {
      q1_score: 'Antara muka sistem mudah difahami.',
      q2_score:
        'Saya boleh menyelesaikan semua operasi dalam sistem dengan lancar.',
      q3_score:
        'Penjelasan untuk kata kunci dan label SRL adalah jelas dan mudah difahami.',
      q4_score:
        'Kandungan kursus yang dicadangkan sejajar dengan matlamat pembelajaran saya.',
      q5_score:
        'Saya boleh menggunakan sistem ini secara bebas tanpa bantuan luar.',
      q6_score: 'Kelajuan pemuatan dan tindak balas sistem adalah memuaskan.',
      q7_score: 'Saya bersedia untuk menggunakan sistem ini sekali lagi.',
      q8_score: 'Saya akan mengesyorkan sistem ini kepada orang lain.',
    },
  },
  button: {
    submit: 'Hantar',
    BatchOperations: 'Operasi Kumpulan',
    SelectAll: 'Pilih Semua',
    Cancel: 'Batal',
    Delete: 'Padam',
  },
  message: {
    evaluate: 'Sila nilai 10 kursus teratas terlebih dahulu',
    submitSuccess: 'Keputusan penilaian dihantar dengan berjaya',
    submitFail: 'Penghantaran gagal, sila cuba lagi kemudian',
    rateEachQuestion: 'Sila beri skor untuk setiap soalan sebelum menghantar～',
    hint: 'Sila lengkapkan kedua-dua soal selidik sebelum menghantar.',
    selectCourse: 'Sila pilih kursus untuk batalkan simpanan',
    cancelSuccess: 'Berjaya batalkan simpanan',
    cancelFail: 'Gagal batalkan simpanan',
  },
  footer: {
    CourseEntry: 'Penyertaan Kursus',
    AboutUs: 'Tentang Kami',
    ContactUs: 'Hubungi Kami',
    PrivacyPolicy: 'Dasar Privasi',
    termsOfUse: 'Syarat Penggunaan',
    HelpCenter: 'Pusat Bantuan',
    Feedback: 'Maklum Balas',
    InfringementComplaint: 'Aduan Pelanggaran',
  },
};
