// zh.js
export default {
  login: {
    login: '登录',
    userName: '用户名',
    password: '密码',
    userLogin: '用户登录',
    welcome: '欢迎回来，请登录您的账号',
    plsInputPhone: '请输入手机号',
    plsInputPassword: '请输入密码',
    Noaccount: '还没有账号？',
    RegisterNow: '立即注册',
    validMobilePhone: '请输入正确的手机号',
    passwordEmpty: '密码不能为空',
    phoneEmpty: '手机号不能为空',
    passwordLength: '密码长度不能少于6位',
    passwordFormat: '密码必须包含字母和数字',
    createAccount: '创建账号',
    wonderfulJourney: '开启你的美好旅程',
    haveAccount: '已有账号？',
    loginNow: '立即登录',
  },
  homePage: {
    homePage: '主页',
    PartnerSchool: '合作院校',
    Courses: '课程',
    SmartClassMatch: '智能课程匹配',
    Questionnaire: '问卷调查',
    MyCourse: '我的课程',
    personInfo: '个人资料',
    MetricAnalysis: '指标分析',
    FeedbackCenter: '反馈中心',
    quit: '安全退出',
  },
  common: {
    inputPlaceholder: '请输入',
    PleaseEnterName: '请输入姓名',
    PleaseSelectGender: '请选择性别',
    PleaseSelectAcademicQualifications: '请选择学历',
    PleaseEnterSchoolCompany: '请输入学校/公司',
    PleaseEnterPosition: '请输入职位',
    PleaseEnterWorkingYears: '请输入工作年限',
    PleaseEnterPhoneNumber: '请输入手机号',
    PleaseEnterEmail: '请输入邮箱',
    PleaseSelectDate: '请选择日期',
    Edit: '编辑',
    Save: '保存',
    PersonalData: '个人资料',
    CourseFilter: '课程筛选',
    CourseResult: '搜索到 {total} 门相关课程',
    person: '人',
    collect: '收藏',
    FeedbackCenter: '反馈中心',
    description:
      '欢迎来到反馈中心！我们将收集您对系统使用体验及学习能力的主观反馈，以优化推荐算法与用户体验。',
    fillIn:
      '点击下方按钮填写问卷，提交后将在下方图表中查看您的反馈结果与趋势。',
    fillQuestionnaire: '填写反馈问卷',
    hint: '提示',
    NoData: '暂无数据',
    RequestCanceled: '请求被取消:',
    loginInvalid: '登录已过期，请重新登录',
    NoPermission: '没有权限访问该资源',
    ServerError: '服务器异常，请稍后再试',
    RequestFailed: '请求失败',
    NetworkAbnormal: '网络异常，请检查连接',
    AvatarSuccessfully: '头像更新成功',
    UploadFailed: '上传失败，请重试',
    UploadFailedFormat: '上传失败，请检查网络或文件格式',
    ImageLimit: '只能上传 JPG/PNG/GIF/WEBP 格式的图片',
    ImageSize: '头像图片大小不能超过 10MB',
    UnnamedUser: '未命名用户',
  },
  option: {
    Male: '男',
    Female: '女',
    JuniorHighSchool: '初中',
    HighSchool: '高中',
    College: '大学专科',
    Undergraduate: '大学本科',
    postgraduate: '研究生',
    PhD: '博士',
  },
  personInfo: {
    personInfo: '个人信息',
    Name: '姓名',
    Gender: '性别',
    EducationalQualifications: '学历',
    'School/Company': '学校/公司',
    Position: '职位',
    WorkingYears: '工作年限',
    Birthday: '生日',
    Area: '地区',
    PhoneNumber: '手机号',
    Email: '邮箱',
  },
  questionnaire: {
    srlSurvey: {
      q1_score:
        '在学习过程中，我通常能够保持动力、兴趣和专注，因为我会设定明确的目标并主动推进学习？',
      q2_score:
        '我是否为自己的学习设定清晰的目标与阶段性计划，并主动跟进任务进度以实现长期学习成果？',
      q3_score:
        '我是否能够合理安排每日时间，避免拖延与低效重复任务，并根据任务优先级优化完成顺序？',
      q4_score:
        '在学习中，我是否能关注自己的注意力状态，适时进行自我检查与学习反馈调整？',
      q5_score:
        '当我遇到学习困难时，我是否愿意主动寻求帮助或提问反馈，并通过交流协作获得支持？',
      q6_score:
        '我是否擅长使用多样的学习策略或技巧（如：拆解任务、使用方法表）提升解决学习问题的能力？',
      q7_score:
        '我是否经常在学习后回顾经验、反思不足，并主动调整策略以持续优化学习方法？',
    },
    dimension: {
      q1_score: '动机调节',
      q2_score: '目标设定',
      q3_score: '时间管理',
      q4_score: '自我监控',
      q5_score: '求助反馈',
      q6_score: '任务策略使用',
      q7_score: '反思调节',
    },
    Satisfaction: {
      StronglyAgree: '非常同意',
      Agree: '同意',
      generally: '一般',
      disagree: '不同意',
      StronglyDisagree: '非常不同意',
      InvalidScore: '无效分数',
    },
    UsabilitySurvey: {
      q1_score: '系统界面易于理解。',
      q2_score: '我能顺利完成系统中的各项操作。',
      q3_score: '关键词和SRL标签解释清晰易懂。',
      q4_score: '推荐的课程内容与我的学习目标一致。',
      q5_score: '我能独立使用该系统，无需外部帮助。',
      q6_score: '系统加载和响应速度令人满意。',
      q7_score: '我愿意再次使用该推荐系统。',
      q8_score: '我会向他人推荐此系统。',
    },
  },
  button: {
    submit: '提交',
    BatchOperations: '批量操作',
    SelectAll: '全选',
    Cancel: '取消',
    Delete: '删除',
  },
  message: {
    evaluate: '请对前10条课程进行评价',
    submitSuccess: '评估结果提交成功',
    submitFail: '提交失败，请稍后再试',
    rateEachQuestion: '请为每一道题目进行评分后再提交～',
    hint: '请先完成两个问卷的填写后再提交。',
    selectCourse: '请先选择要取消收藏的课程',
    cancelSuccess: '取消收藏成功',
    cancelFail: '取消收藏失败',
  },
  footer: {
    CourseEntry: '课程入驻',
    AboutUs: '关于我们',
    ContactUs: '联系我们',
    PrivacyPolicy: '隐私政策',
    termsOfUse: '使用条款',
    HelpCenter: '帮助中心',
    Feedback: '意见反馈',
    InfringementComplaint: '侵权投诉',
  },
};
