// zh.js
export default {
  login: {
    login: '登录',
    userName: '用户名',
    password: '密码',
  },
  homePage: {
    homePage: '主页',
    PartnerSchool: '合作院校',
    Courses: '课程',
    SmartClassMatch: '智能课程匹配',
    Questionnaire: '问卷调查',
    MyCourse: '我的课程',
    personInfo: '个人资料',
    MetricAnalysis: '指标分析',
    FeedbackCenter: '反馈中心',
    quit: '安全退出',
  },
  common: {
    inputPlaceholder: '请输入',
    PleaseEnterName: '请输入姓名',
    PleaseSelectGender: '请选择性别',
    PleaseSelectAcademicQualifications: '请选择学历',
    PleaseEnterSchoolCompany: '请输入学校/公司',
    PleaseEnterPosition: '请输入职位',
    PleaseEnterWorkingYears: '请输入工作年限',
    PleaseEnterPhoneNumber: '请输入手机号',
    PleaseEnterEmail: '请输入邮箱',
    PleaseSelectDate: '请选择日期',
    Edit: '编辑',
    Save: '保存',
    PersonalData: '个人资料',
    CourseFilter: '课程筛选',
    CourseResult: '搜索到 {total} 门相关课程',
  },
  option: {
    Male: '男',
    Female: '女',
    JuniorHighSchool: '初中',
    HighSchool: '高中',
    College: '大学专科',
    Undergraduate: '大学本科',
    postgraduate: '研究生',
    PhD: '博士',
  },
  personInfo: {
    personInfo: '个人信息',
    Name: '姓名',
    Gender: '性别',
    EducationalQualifications: '学历',
    'School/Company': '学校/公司',
    Position: '职位',
    WorkingYears: '工作年限',
    Birthday: '生日',
    Area: '地区',
    PhoneNumber: '手机号',
    Email: '邮箱',
  },
};
