// zh.js
export default {
  login: {
    login: '登录',
    userName: '用户名',
    password: '密码',
  },
  homePage: {
    homePage: '主页',
    PartnerSchool: '合作院校',
    Courses: '课程',
    SmartClassMatch: '智能课程匹配',
    Questionnaire: '问卷调查',
    MyCourse: '我的课程',
    personInfo: '个人资料',
    MetricAnalysis: '指标分析',
    FeedbackCenter: '反馈中心',
    quit: '安全退出',
  },
  common: {
    inputPlaceholder: '请输入',
    PleaseEnterName: '请输入姓名',
    PleaseSelectGender: '请选择性别',
    PleaseSelectAcademicQualifications: '请选择学历',
    PleaseEnterSchoolCompany: '请输入学校/公司',
    PleaseEnterPosition: '请输入职位',
    PleaseEnterWorkingYears: '请输入工作年限',
    PleaseEnterPhoneNumber: '请输入手机号',
    PleaseEnterEmail: '请输入邮箱',
    PleaseSelectDate: '请选择日期',
    Edit: '编辑',
    Save: '保存',
    PersonalData: '个人资料',
    CourseFilter: '课程筛选',
    CourseResult: '搜索到 {total} 门相关课程',
  },
  option: {
    Male: '男',
    Female: '女',
    JuniorHighSchool: '初中',
    HighSchool: '高中',
    College: '大学专科',
    Undergraduate: '大学本科',
    postgraduate: '研究生',
    PhD: '博士',
  },
  personInfo: {
    personInfo: '个人信息',
    Name: '姓名',
    Gender: '性别',
    EducationalQualifications: '学历',
    'School/Company': '学校/公司',
    Position: '职位',
    WorkingYears: '工作年限',
    Birthday: '生日',
    Area: '地区',
    PhoneNumber: '手机号',
    Email: '邮箱',
  },
  questionnaire: {
    srlSurvey: {
      q1_score:
        '在学习过程中，我是否经常因缺乏动力、兴趣或不明确的目标而难以保持主动性与专注力？',
      q2_score:
        '我是否为自己的学习设定清晰的目标与阶段性计划，并主动跟进任务进度以实现长期学习成果？',
      q3_score:
        '我是否能够合理安排每日时间，避免拖延与低效重复任务，并根据任务优先级优化完成顺序？',
      q4_score:
        '在学习中，我是否能关注自己的注意力状态，适时进行自我检查与学习反馈调整？',
      q5_score:
        '当我遇到学习困难时，我是否愿意主动寻求帮助或提问反馈，并通过交流协作获得支持？',
      q6_score:
        '我是否擅长使用多样的学习策略或技巧（如：拆解任务、使用方法表）提升解决学习问题的能力？',
      q7_score:
        '我是否经常在学习后回顾经验、反思不足，并主动调整策略以持续优化学习方法？',
    },
    dimension: {
      q1_score: '动机调节',
      q2_score: '目标设定',
      q3_score: '时间管理',
      q4_score: '自我监控',
      q5_score: '求助反馈',
      q6_score: '任务策略使用',
      q7_score: '反思调节',
    },
    Satisfaction: {
      StronglyAgree: '非常同意',
      Agree: '同意',
      generally: '一般',
      disagree: '不同意',
      StronglyDisagree: '非常不同意',
      InvalidScore: '无效分数',
    },
    UsabilitySurvey: {
      q1_score: '系统界面易于理解。',
      q2_score: '我能顺利完成系统中的各项操作。',
      q3_score: '关键词和SRL标签解释清晰易懂。',
      q4_score: '推荐的课程内容与我的学习目标一致。',
      q5_score: '我能独立使用该系统，无需外部帮助。',
      q6_score: '系统加载和响应速度令人满意。',
      q7_score: '我愿意再次使用该推荐系统。',
      q8_score: '我会向他人推荐此系统。',
    },
  },
};
